from assert_A import assert_A
from assert_B import assert_B
from assert_C import assert_C
from assert_D import assert_D
from assert_E import assert_E
from assert_F import assert_F
from assert_G import assert_G
from assert_H import assert_H
from assert_I import assert_I
from assert_J import assert_J
from assert_K import assert_K
from assert_L import assert_L
from assert_M import assert_M
from assert_N import assert_N
from assert_O import assert_O
from assert_P import assert_P
from assert_Q import assert_Q
from assert_R import assert_R
from assert_S import assert_S
from assert_T import assert_T
from assert_U import assert_U
from assert_V import assert_V
from assert_W import assert_W
from assert_X import assert_X
from assert_Y import assert_Y
from assert_Z import assert_Z